/* Generated by RayTask compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <math.h>
#include <ctype.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#include <time.h>
#endif

/* ---- RayTask native runtime ---- */
static void print(const char* s) { puts(s ? s : "null"); }
static void write(const char* s) { fputs(s ? s : "null", stdout); }
static void print_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void print_f64(double n) { printf("%g\n", n); }
static void print_bool(bool b) { puts(b ? "true" : "false"); }
static void rt_sleep(int ms) {
#ifdef _WIN32
  Sleep((DWORD)ms);
#else
  struct timespec ts; ts.tv_sec = ms / 1000; ts.tv_nsec = (long)(ms % 1000) * 1000000L;
  nanosleep(&ts, NULL);
#endif
}
typedef struct RtGcHdr { struct RtGcHdr* next; int marked; size_t size; } RtGcHdr;
static RtGcHdr* rt_gc_list = NULL;
static size_t rt_gc_bytes = 0;
static size_t rt_gc_threshold = 256 * 1024;
static void* rt_gc_alloc(size_t n) {
  RtGcHdr* h = (RtGcHdr*)malloc(sizeof(RtGcHdr) + n);
  if (!h) return NULL;
  h->next = rt_gc_list; h->marked = 0; h->size = n;
  rt_gc_list = h; rt_gc_bytes += n;
  if (rt_gc_bytes > rt_gc_threshold) { /* threshold hit — caller may Collect */ }
  return (void*)(h + 1);
}
static void* rt_zalloc(size_t n) {
  void* p = rt_gc_alloc(n); if (p) memset(p, 0, n); return p;
}
static void rt_gc_mark_ptr(void* p) {
  if (!p) return;
  RtGcHdr* h = ((RtGcHdr*)p) - 1;
  if (h->marked) return; h->marked = 1;
}
static void Gc_Collect(void) {
  /* Conservative sweep: free unmarked; roots must call rt_gc_mark_ptr */
  RtGcHdr** cur = &rt_gc_list;
  while (*cur) {
    RtGcHdr* h = *cur;
    if (!h->marked) { *cur = h->next; rt_gc_bytes -= h->size; free(h); }
    else { h->marked = 0; cur = &h->next; }
  }
}
static int64_t Gc_Stats(void) { return (int64_t)rt_gc_bytes; }
#define rt_new(T) ((T*)rt_zalloc(sizeof(T)))
typedef struct RtTask {
  int ready;
  void* result;
  int delay_ms;
} RtTask;
static RtTask* rt_task_ready(void* result) {
  RtTask* t = (RtTask*)rt_gc_alloc(sizeof(RtTask));
  t->ready = 1; t->result = result; t->delay_ms = 0; return t;
}
static RtTask* Task_Delay(int ms) {
  RtTask* t = (RtTask*)rt_gc_alloc(sizeof(RtTask));
  t->ready = 0; t->result = NULL; t->delay_ms = ms; return t;
}
static void* rt_await(RtTask* t) {
  if (!t) return NULL;
  if (!t->ready && t->delay_ms > 0) { rt_sleep(t->delay_ms); t->ready = 1; }
  while (!t->ready) { /* cooperative spin */ }
  return t->result;
}
#define await(t) rt_await((RtTask*)(t))
static double Math_Sqrt(double x) { return sqrt(x); }
static double Math_Abs(double x) { return fabs(x); }
static double Math_Pow(double a, double b) { return pow(a, b); }
static double Math_Floor(double x) { return floor(x); }
static double Math_Ceil(double x) { return ceil(x); }
static double Math_Sin(double x) { return sin(x); }
static double Math_Cos(double x) { return cos(x); }
static char* File_ReadText(const char* path) {
  FILE* f = fopen(path, "rb"); if (!f) return NULL;
  fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)rt_gc_alloc((size_t)n + 1); if (!buf) { fclose(f); return NULL; }
  fread(buf, 1, (size_t)n, f); buf[n] = 0; fclose(f); return buf;
}
static void File_WriteText(const char* path, const char* s) {
  FILE* f = fopen(path, "wb"); if (!f) return;
  if (s) fputs(s, f); fclose(f);
}
static void* rt_null_coalesce(void* a, void* b) { return a ? a : b; }

/* import bstd.io */
void Main(void) {
    puts("Hello, RayTask!");
    int64_t x = 10;
    int64_t y = 32;
    printf("10 + 32 = %lld\n", (long long)((x + y)));
    if ((x > 5)) {
        puts("x is greater than 5");
    }
    for (int64_t i = 0; (i < 10000); (i++)) {
        printf("i = %lld\n", (long long)(i));
    }
}

int main(void) { Main(); return 0; }
