/* Generated by RayTask compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <math.h>
#include <ctype.h>

/* ---- RayTask native runtime (bstd.io / math / string) ---- */
static void print(const char* s) { puts(s ? s : "null"); }
static void write(const char* s) { fputs(s ? s : "null", stdout); }
static void print_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void print_f64(double n) { printf("%g\n", n); }
static void print_bool(bool b) { puts(b ? "true" : "false"); }
static void rt_sleep(int ms) {
#ifdef _WIN32
  /* Sleep(ms) — link with kernel32 if needed */
#else
  /* nanosleep omitted in MVP C runtime */
#endif
  (void)ms;
}
static double Math_Sqrt(double x) { return sqrt(x); }
static double Math_Abs(double x) { return fabs(x); }
static double Math_Pow(double a, double b) { return pow(a, b); }
static double Math_Floor(double x) { return floor(x); }
static double Math_Ceil(double x) { return ceil(x); }
static double Math_Sin(double x) { return sin(x); }
static double Math_Cos(double x) { return cos(x); }
static char* File_ReadText(const char* path) {
  FILE* f = fopen(path, "rb"); if (!f) return NULL;
  fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc((size_t)n + 1); if (!buf) { fclose(f); return NULL; }
  fread(buf, 1, (size_t)n, f); buf[n] = 0; fclose(f); return buf;
}
static void File_WriteText(const char* path, const char* s) {
  FILE* f = fopen(path, "wb"); if (!f) return;
  if (s) fputs(s, f); fclose(f);
}
static void* rt_null_coalesce(void* a, void* b) { return a ? a : b; }

/* import bstd.io */
typedef struct Point_s {
    int32_t x;
    int32_t y;
} Point;

Point* Point_new(int32_t x, int32_t y) {
    Point* this = (Point*)calloc(1, sizeof(Point));
    this->x = x;
    this->y = y;
    return this;
}

int32_t Point_Manhattan(Point* this, Point* other) {
    int64_t dx = (this->x - other->x);
    if ((dx < 0)) {
        dx = (-dx);
    }
    int64_t dy = (this->y - other->y);
    if ((dy < 0)) {
        dy = (-dy);
    }
    return (dx + dy);
}

void Main(void) {
    Point* p1 = Point_new(0, 0);
    Point* p2 = Point_new(3, 4);
    int64_t d = Point_Manhattan(p1, p2);
    printf("%lld\n", (long long)(d));
}

int main(void) { Main(); return 0; }
