//! C transpiler for native / wasm / embedded / kernel targets.

use crate::ast::*;
use crate::error::CompileResult;
use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuntimeProfile {
    Host,
    Wasm,
    Embedded,
    Kernel,
}

#[derive(Debug, Clone, Copy)]
pub struct CodegenOptions {
    pub profile: RuntimeProfile,
    pub gc: bool,
    pub freestanding: bool,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            profile: RuntimeProfile::Host,
            gc: true,
            freestanding: false,
        }
    }
}

pub struct CCodegen {
    out: String,
    indent: usize,
    /// Class / struct type names (heap objects → pointers in C).
    types: HashSet<String>,
    /// `[repr: "C"]` / packed / aligned structs and unions — by-value C ABI.
    pod_types: HashSet<String>,
    /// Local variable → C type name (without `*`).
    var_types: HashMap<String, String>,
    /// Current class/struct while emitting a method.
    current_type: Option<String>,
    opts: CodegenOptions,
    /// Pending attributes while emitting nested items.
    pending_interrupt: Option<u64>,
    pending_address: Option<u64>,
    pending_no_gc: bool,
    /// When set, function bodies are emitted from SSA (`emit_c`) instead of AST.
    ssa_bodies: bool,
    /// AST function names whose bodies are provided by SSA (dotted names normalized).
    ssa_fn_names: HashSet<String>,
}

impl CCodegen {
    pub fn new() -> Self {
        Self::with_options(CodegenOptions::default())
    }

    pub fn with_options(opts: CodegenOptions) -> Self {
        Self {
            out: String::new(),
            indent: 0,
            types: HashSet::new(),
            pod_types: HashSet::new(),
            var_types: HashMap::new(),
            current_type: None,
            opts,
            pending_interrupt: None,
            pending_address: None,
            pending_no_gc: false,
            ssa_bodies: false,
            ssa_fn_names: HashSet::new(),
        }
    }

    /// Emit freestanding/host C with function bodies lowered from SSA.
    pub fn generate_with_ssa(
        mut self,
        program: &Program,
        ssa: &crate::ssa::ir::SsaModule,
    ) -> CompileResult<String> {
        self.ssa_bodies = true;
        self.ssa_fn_names = crate::ssa::emit_c::body_function_names(ssa)
            .into_iter()
            .collect();
        // Also accept AST names without dots matching SSA `Type.method` → we match both
        let extra: Vec<String> = self
            .ssa_fn_names
            .iter()
            .filter_map(|n| n.rsplit_once('.').map(|(_, m)| m.to_string()))
            .collect();
        self.ssa_fn_names.extend(extra);

        if program_has_attr(program, "no_gc") {
            self.opts.gc = false;
            self.pending_no_gc = true;
        }
        self.collect_types(program);
        self.writeln("/* Generated by RayTask compiler (SSA → C) */");
        if matches!(
            self.opts.profile,
            RuntimeProfile::Host | RuntimeProfile::Wasm
        ) {
            self.writeln("/* True AOT path: no RTBC interpreter in the final binary */");
        }
        self.emit_includes();
        let mut seen_inc = std::collections::HashSet::new();
        for item in &program.items {
            collect_ffi_headers(item, &mut self.out, &mut seen_inc);
        }
        self.writeln("");
        self.emit_runtime();
        self.writeln("");

        // Forward-declare SSA functions so mutual recursion works
        for f in &ssa.functions {
            if !crate::ssa::emit_c::body_function_names(ssa)
                .iter()
                .any(|n| n == &f.name)
            {
                continue;
            }
            let cname = crate::ssa::emit_c::c_func_name(&f.name);
            // Match emit_c void detection (null returns count as void)
            let ret = {
                let mut returns_val = false;
                for b in f.blocks.values() {
                    if let crate::ssa::ir::Terminator::Return(Some(vid)) = &b.term {
                        let is_null = f.blocks.values().flat_map(|bb| bb.insts.iter()).any(|i| {
                            i.id == *vid
                                && matches!(
                                    i.kind,
                                    crate::ssa::ir::InstKind::Const(
                                        crate::ssa::ir::ConstValue::Null
                                    )
                                )
                        });
                        if !is_null {
                            returns_val = true;
                            break;
                        }
                    }
                }
                if returns_val {
                    "int64_t"
                } else {
                    "void"
                }
            };
            let params: Vec<_> = (0..f.arity).map(|i| format!("int64_t a{i}")).collect();
            let plist = if params.is_empty() {
                "void".into()
            } else {
                params.join(", ")
            };
            self.writeln(&format!("{ret} {cname}({plist});"));
        }
        self.writeln("");

        for item in &program.items {
            self.emit_item(item)?;
        }

        self.out.push_str(&crate::ssa::emit_c::emit_functions(ssa));

        match self.opts.profile {
            RuntimeProfile::Kernel => {
                if !self.out.contains("kmain") && self.out.contains("void Main(") {
                    self.writeln("void kmain(void) { Main(); }");
                }
            }
            RuntimeProfile::Embedded | RuntimeProfile::Wasm => {
                if !self.out.contains("int main(") && self.out.contains("void Main(") {
                    self.writeln("int main(void) { Main(); return 0; }");
                }
            }
            RuntimeProfile::Host => {
                if !self.out.contains("int main(") && self.out.contains("void Main(") {
                    self.writeln("int main(void) { Main(); return 0; }");
                }
            }
        }

        Ok(self.out)
    }

    pub fn generate(mut self, program: &Program) -> CompileResult<String> {
        // File-level [no_gc]
        if program_has_attr(program, "no_gc") {
            self.opts.gc = false;
            self.pending_no_gc = true;
        }
        self.collect_types(program);
        self.writeln("/* Generated by RayTask compiler */");
        self.emit_includes();
        let mut seen_inc = std::collections::HashSet::new();
        for item in &program.items {
            collect_ffi_headers(item, &mut self.out, &mut seen_inc);
        }
        self.writeln("");
        self.emit_runtime();
        self.writeln("");

        for item in &program.items {
            self.emit_item(item)?;
        }

        match self.opts.profile {
            RuntimeProfile::Kernel => {
                if !self.out.contains("kmain") && self.out.contains("void Main(") {
                    self.writeln("void kmain(void) { Main(); }");
                }
            }
            RuntimeProfile::Embedded | RuntimeProfile::Wasm => {
                if !self.out.contains("int main(") && self.out.contains("void Main(") {
                    self.writeln("int main(void) { Main(); return 0; }");
                }
            }
            RuntimeProfile::Host => {
                if !self.out.contains("int main(") && self.out.contains("void Main(") {
                    self.writeln("int main(void) { Main(); return 0; }");
                }
            }
        }

        Ok(self.out)
    }

    fn emit_includes(&mut self) {
        if self.opts.freestanding {
            self.writeln("/* freestanding */");
            self.writeln("#include <stdint.h>");
            self.writeln("#include <stddef.h>");
            self.writeln("#include <stdbool.h>");
            return;
        }
        self.writeln("#include <stdio.h>");
        self.writeln("#include <stdlib.h>");
        self.writeln("#include <stddef.h>");
        self.writeln("#include <string.h>");
        self.writeln("#include <stdbool.h>");
        self.writeln("#include <stdint.h>");
        self.writeln("#include <math.h>");
        self.writeln("#include <ctype.h>");
        if self.opts.profile == RuntimeProfile::Host {
            self.writeln("#ifdef _WIN32");
            self.writeln("#include <windows.h>");
            self.writeln("#else");
            self.writeln("#include <unistd.h>");
            self.writeln("#include <time.h>");
            self.writeln("#endif");
        }
    }

    fn emit_runtime(&mut self) {
        let freestanding = self.opts.freestanding;
        let gc = self.opts.gc && !freestanding;
        self.writeln("/* ---- RayTask native runtime ---- */");

        if freestanding {
            self.writeln("static void print(const char* s) { (void)s; /* no console */ }");
            self.writeln("static void write(const char* s) { (void)s; }");
            self.writeln("static void print_i64(int64_t n) { (void)n; }");
            self.writeln("static void print_f64(double n) { (void)n; }");
            self.writeln("static void print_bool(bool b) { (void)b; }");
            self.writeln("enum { RT_HEAP_BYTES = 65536 };");
            self.writeln("static unsigned char rt_heap[RT_HEAP_BYTES];");
            self.writeln("static size_t rt_heap_off = 0;");
            self.writeln("static void* rt_malloc(size_t n) {");
            self.writeln("  size_t align = 8;");
            self.writeln("  size_t off = (rt_heap_off + (align - 1)) & ~(align - 1);");
            self.writeln("  if (n > RT_HEAP_BYTES || off + n > RT_HEAP_BYTES) return (void*)0;");
            self.writeln("  void* p = &rt_heap[off];");
            self.writeln("  rt_heap_off = off + n;");
            self.writeln("  for (size_t i = 0; i < n; ++i) ((unsigned char*)p)[i] = 0;");
            self.writeln("  return p;");
            self.writeln("}");
            self.writeln("static void rt_free(void* p) { (void)p; /* arena */ }");
            self.writeln("#define calloc(n,s) rt_malloc((n)*(s))");
            self.writeln("#define malloc(n) rt_malloc(n)");
            self.writeln("#define free(p) rt_free(p)");
            self.writeln("static void* memset(void* s, int c, size_t n) {");
            self.writeln("  unsigned char* p = (unsigned char*)s;");
            self.writeln("  for (size_t i = 0; i < n; ++i) p[i] = (unsigned char)c;");
            self.writeln("  return s;");
            self.writeln("}");
            self.writeln("static void* memcpy(void* d, const void* s, size_t n) {");
            self.writeln("  unsigned char* dd = (unsigned char*)d;");
            self.writeln("  const unsigned char* ss = (const unsigned char*)s;");
            self.writeln("  for (size_t i = 0; i < n; ++i) dd[i] = ss[i];");
            self.writeln("  return d;");
            self.writeln("}");
            self.writeln("static void* realloc(void* p, size_t n) {");
            self.writeln("  (void)p; return rt_malloc(n); /* bump arena: old block retained */");
            self.writeln("}");
            // Portable MMIO / busy-wait used by bstd.hal and board BSPs
            self.writeln("static int32_t MmioRead32(int64_t addr) {");
            self.writeln("  return *(volatile int32_t*)(uintptr_t)addr;");
            self.writeln("}");
            self.writeln("static void MmioWrite32(int64_t addr, int32_t value) {");
            self.writeln("  *(volatile int32_t*)(uintptr_t)addr = value;");
            self.writeln("}");
            self.writeln("static void Spin(int32_t cycles) {");
            self.writeln("  for (volatile int32_t i = 0; i < cycles; ++i) {}");
            self.writeln("}");
            self.writeln("static bool IsFreestanding(void) { return true; }");
        } else {
            self.writeln("static void print(const char* s) { puts(s ? s : \"null\"); }");
            self.writeln("static void write(const char* s) { fputs(s ? s : \"null\", stdout); }");
            self.writeln("static void print_i64(int64_t n) { printf(\"%lld\\n\", (long long)n); }");
            self.writeln("static void print_f64(double n) { printf(\"%g\\n\", n); }");
            self.writeln("static void print_bool(bool b) { puts(b ? \"true\" : \"false\"); }");
        }

        self.writeln("static void rt_sleep(int ms) {");
        if freestanding {
            self.writeln("  (void)ms; /* busy-wait hook for board support */");
        } else {
            self.writeln("#ifdef _WIN32");
            self.writeln("  Sleep((DWORD)ms);");
            self.writeln("#else");
            self.writeln("  struct timespec ts; ts.tv_sec = ms / 1000; ts.tv_nsec = (long)(ms % 1000) * 1000000L;");
            self.writeln("  nanosleep(&ts, NULL);");
            self.writeln("#endif");
        }
        self.writeln("}");

        // ---- GC ----
        if gc {
            self.writeln("typedef struct RtGcHdr { struct RtGcHdr* next; int marked; size_t size; } RtGcHdr;");
            self.writeln("static RtGcHdr* rt_gc_list = NULL;");
            self.writeln("static size_t rt_gc_bytes = 0;");
            self.writeln("static size_t rt_gc_threshold = 256 * 1024;");
            self.writeln("static void* rt_gc_alloc(size_t n) {");
            self.writeln("  RtGcHdr* h = (RtGcHdr*)malloc(sizeof(RtGcHdr) + n);");
            self.writeln("  if (!h) return NULL;");
            self.writeln("  h->next = rt_gc_list; h->marked = 0; h->size = n;");
            self.writeln("  rt_gc_list = h; rt_gc_bytes += n;");
            self.writeln("  if (rt_gc_bytes > rt_gc_threshold) { /* threshold hit — caller may Collect */ }");
            self.writeln("  return (void*)(h + 1);");
            self.writeln("}");
            self.writeln("static void* rt_zalloc(size_t n) {");
            self.writeln("  void* p = rt_gc_alloc(n); if (p) memset(p, 0, n); return p;");
            self.writeln("}");
            self.writeln("static void rt_gc_mark_ptr(void* p) {");
            self.writeln("  if (!p) return;");
            self.writeln("  RtGcHdr* h = ((RtGcHdr*)p) - 1;");
            self.writeln("  if (h->marked) return; h->marked = 1;");
            self.writeln("}");
            self.writeln("static void Gc_Collect(void) {");
            self.writeln("  /* Conservative sweep: free unmarked; roots must call rt_gc_mark_ptr */");
            self.writeln("  RtGcHdr** cur = &rt_gc_list;");
            self.writeln("  while (*cur) {");
            self.writeln("    RtGcHdr* h = *cur;");
            self.writeln("    if (!h->marked) { *cur = h->next; rt_gc_bytes -= h->size; free(h); }");
            self.writeln("    else { h->marked = 0; cur = &h->next; }");
            self.writeln("  }");
            self.writeln("}");
            self.writeln("static int64_t Gc_Stats(void) { return (int64_t)rt_gc_bytes; }");
            self.writeln("#define rt_new(T) ((T*)rt_zalloc(sizeof(T)))");
        } else {
            self.writeln("static void Gc_Collect(void) {}");
            self.writeln("static int64_t Gc_Stats(void) { return 0; }");
            if freestanding {
                self.writeln("#define rt_new(T) ((T*)rt_malloc(sizeof(T)))");
            } else {
                self.writeln("#define rt_new(T) ((T*)calloc(1, sizeof(T)))");
            }
        }

        // ---- Async / Task ----
        self.writeln("typedef struct RtCancellationToken RtCancellationToken;");
        self.writeln("typedef struct RtTask RtTask;");
        self.writeln("struct RtTask {");
        self.writeln("  int ready;");
        self.writeln("  int failed;");
        self.writeln("  const char* error;");
        self.writeln("  void* result;");
        self.writeln("  int delay_ms;");
        self.writeln("  RtCancellationToken* cancel_token;");
        self.writeln("};");
        self.writeln("struct RtCancellationToken {");
        self.writeln("  int is_cancelled;");
        self.writeln("  RtTask** tasks;");
        self.writeln("  int task_count;");
        self.writeln("  int task_cap;");
        self.writeln("};");
        self.writeln("typedef struct RtCancellationTokenSource { RtCancellationToken* token; } RtCancellationTokenSource;");
        self.writeln("typedef struct RtTaskGroup { RtCancellationToken* token; RtTask** tasks; int task_count; int task_cap; } RtTaskGroup;");
        self.writeln("static void rt_task_link_token(RtTask* task, RtCancellationToken* token) {");
        self.writeln("  if (!task || !token) return;");
        self.writeln("  task->cancel_token = token;");
        self.writeln("  if (token->task_count >= token->task_cap) {");
        self.writeln("    int next = token->task_cap ? token->task_cap * 2 : 4;");
        self.writeln("    token->tasks = (RtTask**)realloc(token->tasks, (size_t)next * sizeof(RtTask*));");
        self.writeln("    token->task_cap = next;");
        self.writeln("  }");
        self.writeln("  token->tasks[token->task_count++] = task;");
        self.writeln("}");
        self.writeln("static RtTask* rt_task_pending(RtCancellationToken* token) {");
        if freestanding {
            self.writeln("  static RtTask pool[32]; static int pi = 0;");
            self.writeln("  RtTask* t = &pool[pi++ % 32]; memset(t, 0, sizeof(*t)); rt_task_link_token(t, token); return t;");
        } else if gc {
            self.writeln("  RtTask* t = (RtTask*)rt_gc_alloc(sizeof(RtTask)); memset(t, 0, sizeof(*t)); rt_task_link_token(t, token); return t;");
        } else {
            self.writeln("  RtTask* t = (RtTask*)calloc(1, sizeof(RtTask)); rt_task_link_token(t, token); return t;");
        }
        self.writeln("}");
        self.writeln("static RtTask* rt_task_ready(void* result) {");
        if freestanding {
            self.writeln("  static RtTask pool[32]; static int pi = 0;");
            self.writeln("  RtTask* t = &pool[pi++ % 32]; memset(t, 0, sizeof(*t)); t->ready = 1; t->result = result; return t;");
        } else if gc {
            self.writeln("  RtTask* t = (RtTask*)rt_gc_alloc(sizeof(RtTask));");
            self.writeln("  memset(t, 0, sizeof(*t)); t->ready = 1; t->result = result; return t;");
        } else {
            self.writeln("  RtTask* t = (RtTask*)calloc(1, sizeof(RtTask));");
            self.writeln("  t->ready = 1; t->result = result; return t;");
        }
        self.writeln("}");
        self.writeln("static RtTask* rt_task_fail(const char* error) {");
        self.writeln("  RtTask* t = rt_task_ready(NULL); t->failed = 1; t->error = error; return t;");
        self.writeln("}");
        self.writeln("static void rt_cancel_token(RtCancellationToken* token) {");
        self.writeln("  if (!token) return;");
        self.writeln("  token->is_cancelled = 1;");
        self.writeln("  for (int i = 0; i < token->task_count; ++i) {");
        self.writeln("    RtTask* t = token->tasks[i];");
        self.writeln("    if (t && !t->ready) { t->ready = 1; t->failed = 1; t->error = \"operation cancelled\"; }");
        self.writeln("  }");
        self.writeln("}");
        self.writeln("static RtTask* Task_Delay(int ms) {");
        if freestanding {
            self.writeln("  static RtTask pool[8]; static int pi = 0;");
            self.writeln("  RtTask* t = &pool[pi++ % 8]; memset(t, 0, sizeof(*t)); t->delay_ms = ms; return t;");
        } else if gc {
            self.writeln("  RtTask* t = rt_task_pending(NULL);");
            self.writeln("  t->delay_ms = ms; return t;");
        } else {
            self.writeln("  RtTask* t = rt_task_pending(NULL);");
            self.writeln("  t->delay_ms = ms; return t;");
        }
        self.writeln("}");
        self.writeln("static void* rt_await(RtTask* t) {");
        self.writeln("  if (!t) return NULL;");
        self.writeln("  if (t->cancel_token && t->cancel_token->is_cancelled && !t->ready) { t->ready = 1; t->failed = 1; t->error = \"operation cancelled\"; }");
        self.writeln("  if (!t->ready && t->delay_ms > 0) { rt_sleep(t->delay_ms); t->ready = 1; }");
        self.writeln("  while (!t->ready) { /* cooperative spin */ }");
        self.writeln("  if (t->failed) return NULL;");
        self.writeln("  return t->result;");
        self.writeln("}");
        self.writeln("static RtTask* Task_WhenAll(RtTask** tasks, int count) {");
        self.writeln("  for (int i = 0; i < count; ++i) { if (tasks[i]) rt_await(tasks[i]); if (tasks[i] && tasks[i]->failed) return rt_task_fail(tasks[i]->error); }");
        self.writeln("  return rt_task_ready(NULL);");
        self.writeln("}");
        self.writeln("static RtTask* Task_WhenAny(RtTask** tasks, int count) {");
        self.writeln("  if (count <= 0) return rt_task_ready(NULL);");
        self.writeln("  if (tasks[0]) rt_await(tasks[0]);");
        self.writeln("  return tasks[0] && tasks[0]->failed ? rt_task_fail(tasks[0]->error) : rt_task_ready(tasks[0] ? tasks[0]->result : NULL);");
        self.writeln("}");
        self.writeln("static RtCancellationTokenSource* CancellationTokenSource_New(void) {");
        if freestanding {
            self.writeln("  static RtCancellationTokenSource src_pool[8]; static RtCancellationToken token_pool[8]; static int pi = 0;");
            self.writeln("  RtCancellationTokenSource* s = &src_pool[pi % 8]; RtCancellationToken* t = &token_pool[pi % 8]; ++pi; memset(s, 0, sizeof(*s)); memset(t, 0, sizeof(*t)); s->token = t; return s;");
        } else if gc {
            self.writeln("  RtCancellationTokenSource* s = (RtCancellationTokenSource*)rt_gc_alloc(sizeof(RtCancellationTokenSource));");
            self.writeln("  RtCancellationToken* t = (RtCancellationToken*)rt_gc_alloc(sizeof(RtCancellationToken));");
            self.writeln("  memset(s, 0, sizeof(*s)); memset(t, 0, sizeof(*t)); s->token = t; return s;");
        } else {
            self.writeln("  RtCancellationTokenSource* s = (RtCancellationTokenSource*)calloc(1, sizeof(RtCancellationTokenSource));");
            self.writeln("  RtCancellationToken* t = (RtCancellationToken*)calloc(1, sizeof(RtCancellationToken));");
            self.writeln("  s->token = t; return s;");
        }
        self.writeln("}");
        self.writeln("static RtCancellationToken* CancellationTokenSource_Token(RtCancellationTokenSource* src) { return src ? src->token : NULL; }");
        self.writeln("static void CancellationTokenSource_Cancel(RtCancellationTokenSource* src) { if (src) rt_cancel_token(src->token); }");
        self.writeln("static bool CancellationToken_IsCancellationRequested(RtCancellationToken* token) { return token && token->is_cancelled; }");
        self.writeln("static void CancellationToken_ThrowIfCancellationRequested(RtCancellationToken* token) { (void)token; }");
        self.writeln("static RtTaskGroup* TaskGroup_New(void) {");
        if freestanding {
            self.writeln("  static RtTaskGroup groups[8]; static RtCancellationToken tokens[8]; static int gi = 0;");
            self.writeln("  RtTaskGroup* g = &groups[gi % 8]; RtCancellationToken* t = &tokens[gi % 8]; ++gi; memset(g, 0, sizeof(*g)); memset(t, 0, sizeof(*t)); g->token = t; return g;");
        } else if gc {
            self.writeln("  RtTaskGroup* g = (RtTaskGroup*)rt_gc_alloc(sizeof(RtTaskGroup));");
            self.writeln("  RtCancellationToken* t = (RtCancellationToken*)rt_gc_alloc(sizeof(RtCancellationToken));");
            self.writeln("  memset(g, 0, sizeof(*g)); memset(t, 0, sizeof(*t)); g->token = t; return g;");
        } else {
            self.writeln("  RtTaskGroup* g = (RtTaskGroup*)calloc(1, sizeof(RtTaskGroup));");
            self.writeln("  RtCancellationToken* t = (RtCancellationToken*)calloc(1, sizeof(RtCancellationToken));");
            self.writeln("  g->token = t; return g;");
        }
        self.writeln("}");
        self.writeln("static RtTask* TaskGroup_Run(RtTaskGroup* group, RtTask* task) {");
        self.writeln("  if (!group) return task;");
        self.writeln("  if (group->task_count >= group->task_cap) { int next = group->task_cap ? group->task_cap * 2 : 4; group->tasks = (RtTask**)realloc(group->tasks, (size_t)next * sizeof(RtTask*)); group->task_cap = next; }");
        self.writeln("  if (task) { rt_task_link_token(task, group->token); group->tasks[group->task_count++] = task; }");
        self.writeln("  return task;");
        self.writeln("}");
        self.writeln("static void TaskGroup_Cancel(RtTaskGroup* group) { if (group) rt_cancel_token(group->token); }");
        self.writeln("static RtTask* TaskGroup_WhenAll(RtTaskGroup* group) { return group ? Task_WhenAll(group->tasks, group->task_count) : rt_task_ready(NULL); }");
        self.writeln("static RtTask* TaskGroup_WhenAny(RtTaskGroup* group) { return group ? Task_WhenAny(group->tasks, group->task_count) : rt_task_ready(NULL); }");
        self.writeln("#define await(t) rt_await((RtTask*)(t))");

        if !freestanding {
            self.writeln("static double Math_Sqrt(double x) { return sqrt(x); }");
            self.writeln("static double Math_Abs(double x) { return fabs(x); }");
            self.writeln("static double Math_Pow(double a, double b) { return pow(a, b); }");
            self.writeln("static double Math_Floor(double x) { return floor(x); }");
            self.writeln("static double Math_Ceil(double x) { return ceil(x); }");
            self.writeln("static double Math_Sin(double x) { return sin(x); }");
            self.writeln("static double Math_Cos(double x) { return cos(x); }");
            self.writeln("static char* File_ReadText(const char* path) {");
            self.writeln("  FILE* f = fopen(path, \"rb\"); if (!f) return NULL;");
            self.writeln("  fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);");
            if gc {
                self.writeln("  char* buf = (char*)rt_gc_alloc((size_t)n + 1); if (!buf) { fclose(f); return NULL; }");
            } else {
                self.writeln("  char* buf = (char*)malloc((size_t)n + 1); if (!buf) { fclose(f); return NULL; }");
            }
            self.writeln("  fread(buf, 1, (size_t)n, f); buf[n] = 0; fclose(f); return buf;");
            self.writeln("}");
            self.writeln("static void File_WriteText(const char* path, const char* s) {");
            self.writeln("  FILE* f = fopen(path, \"wb\"); if (!f) return;");
            self.writeln("  if (s) fputs(s, f); fclose(f);");
            self.writeln("}");
        }
        self.writeln("static void* rt_null_coalesce(void* a, void* b) { return a ? a : b; }");
    }

    fn collect_types(&mut self, program: &Program) {
        fn walk(item: &Item, types: &mut HashSet<String>, pod: &mut HashSet<String>) {
            match item {
                Item::Attribute(_, inner) => walk(inner, types, pod),
                Item::Namespace(ns) => {
                    for i in &ns.items {
                        walk(i, types, pod);
                    }
                }
                Item::Class(c) => {
                    types.insert(c.name.clone());
                }
                Item::Struct(s) => {
                    types.insert(s.name.clone());
                    if s.repr_c || s.packed || s.align.is_some() {
                        pod.insert(s.name.clone());
                    }
                }
                Item::Union(u) => {
                    types.insert(u.name.clone());
                    pod.insert(u.name.clone());
                }
                _ => {}
            }
        }
        for item in &program.items {
            walk(item, &mut self.types, &mut self.pod_types);
        }
    }

    fn ex(&self, expr: &Expr) -> String {
        expr_to_c(
            expr,
            &self.types,
            &self.var_types,
            self.current_type.as_deref(),
        )
    }

    fn writeln(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn emit_item(&mut self, item: &Item) -> CompileResult<()> {
        match item {
            Item::Attribute(attr, inner) => {
                let key = attr.name.to_ascii_lowercase();
                if matches!(key.as_str(), "c" | "cembed" | "embed") {
                    if let Some(src) = crate::ffi::attr_string(attr) {
                        self.writeln("/* ---- embedded C ---- */");
                        self.out.push_str(&src);
                        if !src.ends_with('\n') {
                            self.out.push('\n');
                        }
                        self.writeln("/* ---- end embedded C ---- */");
                        self.writeln("");
                    }
                }
                if matches!(key.as_str(), "link" | "dllimport" | "lib") {
                    if let Some(lib) = crate::ffi::attr_string(attr) {
                        self.writeln(&format!("/* link: {} */", lib));
                    }
                }
                if key == "no_gc" {
                    self.opts.gc = false;
                    self.pending_no_gc = true;
                }
                if key == "interrupt" {
                    self.pending_interrupt = attr_u64(attr);
                }
                if key == "address" {
                    self.pending_address = attr_u64(attr);
                }
                if key == "target" {
                    if let Some(t) = crate::ffi::attr_string(attr) {
                        self.writeln(&format!("/* target: {} */", t));
                    }
                }
                let r = self.emit_item(inner);
                self.pending_interrupt = None;
                self.pending_address = None;
                r
            }
            Item::Namespace(ns) => {
                self.writeln(&format!("/* namespace {} */", ns.name));
                for i in &ns.items {
                    self.emit_item(i)?;
                }
                Ok(())
            }
            Item::Function(f) => self.emit_function(f),
            Item::Class(c) => self.emit_class(c),
            Item::Struct(s) => {
                let addr = self.pending_address.take();
                self.emit_struct(s)?;
                if let Some(a) = addr {
                    self.writeln(&format!(
                        "#define {}_ADDR ((volatile {}*)(uintptr_t)0x{:X})",
                        s.name, s.name, a
                    ));
                    self.writeln(&format!(
                        "static inline volatile {}* {}_mmio(void) {{ return {}_ADDR; }}",
                        s.name, s.name, s.name
                    ));
                    self.writeln("");
                }
                Ok(())
            }
            Item::Union(u) => self.emit_union(u),
            Item::Const(c) => {
                self.writeln(&format!(
                    "const {} {} = {};",
                    c_type(&c.ty),
                    c.name,
                    self.ex(&c.value)
                ));
                Ok(())
            }
            Item::Import(i) => {
                self.writeln(&format!("/* import {} */", i.path));
                Ok(())
            }
            _ => Ok(()),
        }
    }

    fn emit_function(&mut self, f: &FunctionDecl) -> CompileResult<()> {
        let export = f
            .attributes
            .iter()
            .find(|a| {
                matches!(
                    a.name.to_ascii_lowercase().as_str(),
                    "export" | "entry" | "symbol" | "name"
                )
            })
            .and_then(crate::ffi::attr_string);

        let interrupt = f
            .attributes
            .iter()
            .find(|a| a.name.eq_ignore_ascii_case("interrupt"))
            .and_then(attr_u64)
            .or(self.pending_interrupt);

        // Bodies come from SSA — skip AST lowering (prototypes already emitted).
        if self.ssa_bodies && f.body.is_some() {
            let key = if let Some(ct) = &self.current_type {
                format!("{}.{}", ct, f.name)
            } else {
                f.name.clone()
            };
            if self.ssa_fn_names.contains(&f.name) || self.ssa_fn_names.contains(&key) {
                return Ok(());
            }
        }

        if f.body.is_none() && !f.is_abstract {
            let ret = c_type_abi(&f.return_type, &self.types, &self.pod_types, true);
            let params: Vec<_> = f
                .params
                .iter()
                .map(|p| {
                    format!(
                        "{} {}",
                        c_type_abi(&p.ty, &self.types, &self.pod_types, true),
                        p.name
                    )
                })
                .collect();
            let param_list = if params.is_empty() {
                "void".into()
            } else {
                params.join(", ")
            };
            let name = export.as_deref().unwrap_or(&f.name);
            self.writeln(&format!("extern {} {}({});", ret, name, param_list));
            if let Some(exp) = &export {
                if *exp != f.name {
                    self.writeln(&format!("#define {} {}", f.name, exp));
                }
            }
            self.writeln("");
            return Ok(());
        }

        let ret = if f.is_async {
            "RtTask*".to_string()
        } else {
            c_type(&f.return_type)
        };
        let name = if f.name == "Main" {
            "Main"
        } else {
            export.as_deref().unwrap_or(&f.name)
        };
        let params: Vec<_> = f
            .params
            .iter()
            .map(|p| format!("{} {}", c_type_in(&p.ty, &self.types), p.name))
            .collect();
        let param_list = if params.is_empty() {
            "void".into()
        } else {
            params.join(", ")
        };
        if let Some(exp) = &export {
            self.writeln(&format!("/* export: {} */", exp));
        }
        if let Some(vec) = interrupt {
            self.writeln(&format!("/* interrupt vector 0x{:X} */", vec));
            self.writeln(&format!(
                "__attribute__((section(\".text.isr.0x{:X}\"))) {} {}({}) {{",
                vec, ret, name, param_list
            ));
        } else {
            self.writeln(&format!("{} {}({}) {{", ret, name, param_list));
        }
        self.indent += 1;
        self.var_types.clear();
        for p in &f.params {
            let tn = p.ty.name.clone();
            if self.types.contains(&tn) || p.is_this {
                self.var_types.insert(p.name.clone(), tn);
            }
        }
        if let Some(body) = &f.body {
            match body {
                FunctionBody::Block(b) => {
                    if f.is_async {
                        self.emit_block_async(b)?;
                    } else {
                        self.emit_block(b)?;
                    }
                }
                FunctionBody::Expr(e) => {
                    if f.is_async {
                        self.writeln(&format!(
                            "return rt_task_ready((void*)(uintptr_t)({}));",
                            self.ex(e)
                        ));
                    } else {
                        self.writeln(&format!("return {};", self.ex(e)));
                    }
                }
            }
        }
        if f.is_async {
            self.writeln("return rt_task_ready(NULL);");
        }
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
        Ok(())
    }

    fn emit_class(&mut self, c: &ClassDecl) -> CompileResult<()> {
        self.emit_type_body(&c.name, &c.members, false, false, None)
    }

    fn emit_struct(&mut self, s: &StructDecl) -> CompileResult<()> {
        self.emit_type_body(&s.name, &s.members, false, s.packed, s.align)
    }

    fn emit_union(&mut self, u: &UnionDecl) -> CompileResult<()> {
        self.emit_type_body(&u.name, &u.members, true, u.packed, u.align)
    }

    fn emit_type_body(
        &mut self,
        type_name: &str,
        members: &[Member],
        is_union: bool,
        packed: bool,
        align: Option<u32>,
    ) -> CompileResult<()> {
        let kind = if is_union { "union" } else { "struct" };
        if packed {
            self.writeln("#pragma pack(push, 1)");
        }
        self.writeln(&format!("typedef {} {}_s {{", kind, type_name));
        self.indent += 1;
        for m in members {
            if let Member::Field(f) = m {
                let ty = f
                    .ty
                    .as_ref()
                    .map(|t| c_type_abi(t, &self.types, &self.pod_types, true))
                    .unwrap_or_else(|| "void*".into());
                self.writeln(&format!("{} {};", ty, f.name));
            }
            if let Member::Property(p) = m {
                if p.auto {
                    self.writeln(&format!(
                        "{} {};",
                        c_type_abi(&p.ty, &self.types, &self.pod_types, true),
                        p.name
                    ));
                }
            }
        }
        self.indent -= 1;
        if let Some(a) = align {
            self.writeln(&format!(
                "}} __attribute__((aligned({}))) {};",
                a, type_name
            ));
        } else {
            self.writeln(&format!("}} {};", type_name));
        }
        if packed {
            self.writeln("#pragma pack(pop)");
        }
        self.writeln("");

        if is_union {
            return Ok(());
        }

        for m in members {
            match m {
                Member::Method(f) => {
                    if self.ssa_bodies {
                        let key = format!("{}.{}", type_name, f.name);
                        if self.ssa_fn_names.contains(&key) {
                            continue;
                        }
                    }
                    let mut f2 = f.clone();
                    f2.name = format!("{}_{}", type_name, f.name);
                    f2.params.insert(
                        0,
                        Param {
                            is_params: false,
                            is_this: true,
                            name: "this".into(),
                            ty: TypeRef::named(type_name, f.span),
                            default: None,
                            span: f.span,
                        },
                    );
                    self.current_type = Some(type_name.to_string());
                    self.emit_function(&f2)?;
                    self.current_type = None;
                }
                Member::Constructor(ctor) => {
                    if self.ssa_bodies
                        && self
                            .ssa_fn_names
                            .contains(&format!("{}.new", type_name))
                    {
                        continue;
                    }
                    let params: Vec<_> = ctor
                        .params
                        .iter()
                        .map(|p| format!("{} {}", c_type(&p.ty), p.name))
                        .collect();
                    self.writeln(&format!(
                        "{}* {}_new({}) {{",
                        type_name,
                        type_name,
                        if params.is_empty() {
                            "void".into()
                        } else {
                            params.join(", ")
                        }
                    ));
                    self.indent += 1;
                    self.var_types.clear();
                    self.var_types
                        .insert("this".into(), type_name.to_string());
                    for p in &ctor.params {
                        if self.types.contains(&p.ty.name) {
                            self.var_types.insert(p.name.clone(), p.ty.name.clone());
                        }
                    }
                    self.current_type = Some(type_name.to_string());
                    self.writeln(&format!(
                        "{}* this = rt_new({});",
                        type_name, type_name
                    ));
                    self.emit_block(&ctor.body)?;
                    self.writeln("return this;");
                    self.current_type = None;
                    self.indent -= 1;
                    self.writeln("}");
                    self.writeln("");
                }
                Member::Operator(op) => {
                    let params: Vec<_> = op
                        .params
                        .iter()
                        .map(|p| format!("{} {}", c_type(&p.ty), p.name))
                        .collect();
                    let cname = format!(
                        "{}_operator_{}",
                        type_name,
                        op.op
                            .chars()
                            .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
                            .collect::<String>()
                    );
                    self.writeln(&format!(
                        "{} {}({}{} {}) {{",
                        c_type(&op.return_type),
                        cname,
                        format!("{}* this", type_name),
                        if params.is_empty() { "" } else { ", " },
                        params.join(", ")
                    ));
                    self.indent += 1;
                    self.var_types.clear();
                    self.var_types
                        .insert("this".into(), type_name.to_string());
                    self.current_type = Some(type_name.to_string());
                    self.emit_block(&op.body)?;
                    self.current_type = None;
                    self.indent -= 1;
                    self.writeln("}");
                    self.writeln("");
                }
                _ => {}
            }
        }
        Ok(())
    }

    fn emit_block(&mut self, block: &Block) -> CompileResult<()> {
        for stmt in &block.stmts {
            self.emit_stmt(stmt)?;
        }
        Ok(())
    }

    fn emit_block_async(&mut self, block: &Block) -> CompileResult<()> {
        for stmt in &block.stmts {
            match stmt {
                Stmt::Return(e, _) => {
                    if let Some(e) = e {
                        self.writeln(&format!(
                            "return rt_task_ready((void*)(uintptr_t)({}));",
                            self.ex(e)
                        ));
                    } else {
                        self.writeln("return rt_task_ready(NULL);");
                    }
                }
                _ => self.emit_stmt(stmt)?,
            }
        }
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> CompileResult<()> {
        match stmt {
            Stmt::Expr(e) => {
                if let Expr::Call { callee, args, .. } = e {
                    if let Expr::Ident(name, _) = callee.as_ref() {
                        if name == "print" || name == "write" {
                            self.emit_io_call(name, args)?;
                            return Ok(());
                        }
                    }
                }
                self.writeln(&format!("{};", self.ex(e)));
            }
            Stmt::Decl(d) => {
                let ty = d
                    .ty
                    .as_ref()
                    .map(|t| c_type_in(t, &self.types))
                    .unwrap_or_else(|| "int64_t".to_string());
                let ty = if ty == "auto" || d.kind == VarKind::Var || d.kind == VarKind::Dyn {
                    infer_c_type(d.init.as_ref(), &self.types).unwrap_or_else(|| "int64_t".into())
                } else {
                    ty
                };
                if let Some(tname) = d.ty.as_ref().map(|t| t.name.clone()) {
                    if self.types.contains(&tname) {
                        self.var_types.insert(d.name.clone(), tname);
                    }
                } else if let Some(Expr::New { ty: nt, .. }) = &d.init {
                    if self.types.contains(&nt.name) {
                        self.var_types.insert(d.name.clone(), nt.name.clone());
                    }
                }
                if let Some(init) = &d.init {
                    if let Expr::Interpolated(parts, _) = init {
                        let (fmt, args) = interpolate_printf(
                            parts,
                            false,
                            &self.types,
                            &self.var_types,
                            self.current_type.as_deref(),
                        );
                        self.writeln(&format!("char {}[512];", d.name));
                        if args.is_empty() {
                            self.writeln(&format!(
                                "snprintf({}, sizeof({}), \"%s\", {});",
                                d.name, d.name, fmt
                            ));
                        } else {
                            self.writeln(&format!(
                                "snprintf({}, sizeof({}), {}, {});",
                                d.name,
                                d.name,
                                fmt,
                                args.join(", ")
                            ));
                        }
                    } else {
                        self.writeln(&format!("{} {} = {};", ty, d.name, self.ex(init)));
                    }
                } else {
                    self.writeln(&format!("{} {};", ty, d.name));
                }
            }
            Stmt::Return(e, _) => {
                if let Some(e) = e {
                    self.writeln(&format!("return {};", self.ex(e)));
                } else {
                    self.writeln("return;");
                }
            }
            Stmt::If {
                cond,
                then_block,
                else_branch,
                ..
            } => {
                self.writeln(&format!("if ({}) {{", self.ex(cond)));
                self.indent += 1;
                self.emit_block(then_block)?;
                self.indent -= 1;
                self.writeln("}");
                if let Some(e) = else_branch {
                    match e {
                        ElseBranch::Block(b) => {
                            self.writeln("else {");
                            self.indent += 1;
                            self.emit_block(b)?;
                            self.indent -= 1;
                            self.writeln("}");
                        }
                        ElseBranch::If(s) => {
                            self.writeln("else");
                            self.emit_stmt(s)?;
                        }
                    }
                }
            }
            Stmt::While { cond, body, .. } => {
                self.writeln(&format!("while ({}) {{", self.ex(cond)));
                self.indent += 1;
                self.emit_block(body)?;
                self.indent -= 1;
                self.writeln("}");
            }
            Stmt::For {
                init,
                cond,
                step,
                body,
                ..
            } => {
                let mut line = String::from("for (");
                if let Some(i) = init {
                    if let Stmt::Decl(d) = i.as_ref() {
                        let _ = write!(
                            line,
                            "int64_t {} = {}",
                            d.name,
                            d.init
                                .as_ref()
                                .map(|e| self.ex(e))
                                .unwrap_or_else(|| "0".into())
                        );
                    }
                }
                line.push(';');
                if let Some(c) = cond {
                    let _ = write!(line, " {}", self.ex(c));
                }
                line.push(';');
                if let Some(s) = step {
                    let _ = write!(line, " {}", self.ex(s));
                }
                line.push_str(") {");
                self.writeln(&line);
                self.indent += 1;
                self.emit_block(body)?;
                self.indent -= 1;
                self.writeln("}");
            }
            Stmt::DoWhile { body, cond, .. } => {
                self.writeln("do {");
                self.indent += 1;
                self.emit_block(body)?;
                self.indent -= 1;
                self.writeln(&format!("}} while ({});", self.ex(cond)));
            }
            Stmt::Foreach {
                var_name,
                iter,
                body,
                ..
            } => {
                // Best-effort: C99 for-loop over pointer+Count if present
                self.writeln(&format!("/* foreach {} */ {{", var_name));
                self.indent += 1;
                self.writeln(&format!(
                    "void* __iter = (void*)(uintptr_t)({}); (void)__iter;",
                    self.ex(iter)
                ));
                self.writeln(&format!("for (int64_t __i = 0; __i < 0; __i++) {{"));
                self.indent += 1;
                self.writeln(&format!("int64_t {} = 0; (void){};", var_name, var_name));
                self.emit_block(body)?;
                self.indent -= 1;
                self.writeln("}");
                self.indent -= 1;
                self.writeln("}");
            }
            Stmt::Block(b) => {
                self.writeln("{");
                self.indent += 1;
                self.emit_block(b)?;
                self.indent -= 1;
                self.writeln("}");
            }
            Stmt::Unsafe(b, _) => {
                self.writeln("/* unsafe */");
                self.emit_block(b)?;
            }
            Stmt::Asm { template, .. } => {
                self.writeln(&format!("__asm__ volatile (\"{}\");", escape_c(template)));
            }
            Stmt::Break(_) => self.writeln("break;"),
            Stmt::Continue(_) => self.writeln("continue;"),
            other => {
                self.writeln(&format!(
                    "/* unsupported stmt {:?} */",
                    std::mem::discriminant(other)
                ));
            }
        }
        Ok(())
    }

    fn emit_io_call(&mut self, name: &str, args: &[Arg]) -> CompileResult<()> {
        let newline = name == "print";
        if args.is_empty() {
            if newline {
                self.writeln("putchar('\\n');");
            }
            return Ok(());
        }

        // Join multiple args with space (like the VM)
        if args.len() > 1 {
            for (i, a) in args.iter().enumerate() {
                if i > 0 {
                    self.writeln("fputs(\" \", stdout);");
                }
                self.emit_io_value(&a.value, false)?;
            }
            if newline {
                self.writeln("putchar('\\n');");
            }
            return Ok(());
        }

        self.emit_io_value(&args[0].value, newline)?;
        Ok(())
    }

    fn emit_io_value(&mut self, expr: &Expr, newline: bool) -> CompileResult<()> {
        match expr {
            Expr::Interpolated(parts, _) => {
                let (fmt, args) = interpolate_printf(
                    parts,
                    newline,
                    &self.types,
                    &self.var_types,
                    self.current_type.as_deref(),
                );
                if args.is_empty() {
                    if newline {
                        // fmt includes \n — use printf or puts
                        let inner = fmt.trim_matches('"');
                        if let Some(stripped) = inner.strip_suffix("\\n") {
                            self.writeln(&format!("puts(\"{}\");", stripped));
                        } else {
                            self.writeln(&format!("printf({});", fmt));
                        }
                    } else {
                        self.writeln(&format!("printf(\"%s\", {});", fmt));
                    }
                } else {
                    self.writeln(&format!("printf({}, {});", fmt, args.join(", ")));
                }
            }
            Expr::String(s, _) => {
                if newline {
                    self.writeln(&format!("puts(\"{}\");", escape_c(s)));
                } else {
                    self.writeln(&format!("fputs(\"{}\", stdout);", escape_c(s)));
                }
            }
            Expr::Int(n, _) => {
                if newline {
                    self.writeln(&format!("print_i64({});", n));
                } else {
                    self.writeln(&format!("printf(\"%lld\", (long long){});", n));
                }
            }
            Expr::Float(n, _) => {
                if newline {
                    self.writeln(&format!("print_f64({});", n));
                } else {
                    self.writeln(&format!("printf(\"%g\", (double){});", n));
                }
            }
            Expr::Bool(b, _) => {
                if newline {
                    self.writeln(&format!("print_bool({});", b));
                } else {
                    self.writeln(&format!("fputs({}, stdout);", if *b { "\"true\"" } else { "\"false\"" }));
                }
            }
            other => {
                let (spec, arg) = printf_arg(
                    other,
                    &self.types,
                    &self.var_types,
                    self.current_type.as_deref(),
                );
                if newline {
                    self.writeln(&format!("printf(\"%{}\\n\", {});", spec, arg));
                } else {
                    self.writeln(&format!("printf(\"%{}\", {});", spec, arg));
                }
            }
        }
        Ok(())
    }
}

impl Default for CCodegen {
    fn default() -> Self {
        Self::new()
    }
}

fn c_type(ty: &TypeRef) -> String {
    c_type_in(ty, &HashSet::new())
}

/// Prefer by-value for POD (`repr_c` / packed / union) when `by_value` is set.
fn c_type_abi(
    ty: &TypeRef,
    types: &HashSet<String>,
    pod: &HashSet<String>,
    by_value: bool,
) -> String {
    if by_value && pod.contains(&ty.name) {
        let mut s = ty.name.clone();
        if ty.volatile {
            s = format!("volatile {}", s);
        }
        return s;
    }
    c_type_in(ty, types)
}

/// Type name suitable for sizeof/offsetof (no trailing `*` for named records).
fn c_type_sizeof(ty: &TypeRef, types: &HashSet<String>) -> String {
    if types.contains(&ty.name) {
        return ty.name.clone();
    }
    let mut s = c_type_in(ty, types);
    if s.ends_with('*') && ty.name != "ptr" && ty.name != "string" {
        s.pop();
    }
    s
}

fn c_type_in(ty: &TypeRef, types: &HashSet<String>) -> String {
    if types.contains(&ty.name) {
        let mut s = format!("{}*", ty.name);
        if ty.volatile {
            s = format!("volatile {}", s);
        }
        return s;
    }
    let base = match ty.name.as_str() {
        "void" => "void",
        "bool" => "bool",
        "byte" | "uint8" => "uint8_t",
        "sbyte" => "int8_t",
        "short" => "int16_t",
        "ushort" => "uint16_t",
        "int" => "int32_t",
        "uint" => "uint32_t",
        "long" => "int64_t",
        "ulong" => "uint64_t",
        "float" => "float",
        "double" => "double",
        "char" => "uint16_t",
        "string" => "const char*",
        "ptr" => "void*",
        other => other,
    };
    let mut s = base.to_string();
    if ty.is_array {
        s.push('*');
    }
    if !ty.args.is_empty() && ty.name == "ptr" {
        s = format!("{}*", c_type_in(&ty.args[0], types));
    }
    if ty.volatile {
        s = format!("volatile {}", s);
    }
    s
}

fn lookup_type(
    expr: &Expr,
    types: &HashSet<String>,
    vars: &HashMap<String, String>,
    current: Option<&str>,
) -> Option<String> {
    match expr {
        Expr::Ident(n, _) => vars.get(n).cloned(),
        Expr::This(_) => current.map(|s| s.to_string()),
        Expr::New { ty, .. } => {
            if types.contains(&ty.name) {
                Some(ty.name.clone())
            } else {
                None
            }
        }
        Expr::Grouped(e, _) => lookup_type(e, types, vars, current),
        _ => None,
    }
}

fn expr_to_c(
    expr: &Expr,
    types: &HashSet<String>,
    vars: &HashMap<String, String>,
    current: Option<&str>,
) -> String {
    let ex = |e: &Expr| expr_to_c(e, types, vars, current);
    match expr {
        Expr::Int(n, _) => n.to_string(),
        Expr::UInt(n, _) => n.to_string(),
        Expr::Float(n, _) => format!("{}", n),
        Expr::Bool(b, _) => if *b { "true" } else { "false" }.into(),
        Expr::Char(c, _) => format!("'{}'", c),
        Expr::String(s, _) => format!("\"{}\"", escape_c(s)),
        Expr::Null(_) => "NULL".into(),
        Expr::Ident(n, _) => n.clone(),
        Expr::This(_) => "this".into(),
        Expr::Binary { left, op, right, .. } => {
            if *op == BinOp::NullCoalesce {
                return format!("(({}) ? ({}) : ({}))", ex(left), ex(left), ex(right));
            }
            let o = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
                BinOp::BitAnd => "&",
                BinOp::BitOr => "|",
                BinOp::BitXor => "^",
                BinOp::Shl => "<<",
                BinOp::Shr => ">>",
                BinOp::NullCoalesce => unreachable!(),
            };
            format!("({} {} {})", ex(left), o, ex(right))
        }
        Expr::Unary { op, expr, .. } => {
            let o = match op {
                UnOp::Neg => "-",
                UnOp::Not => "!",
                UnOp::BitNot => "~",
                UnOp::PreInc => "++",
                UnOp::PreDec => "--",
                UnOp::PostInc => {
                    return format!("({}++)", ex(expr));
                }
                UnOp::PostDec => {
                    return format!("({}--)", ex(expr));
                }
            };
            format!("({}{})", o, ex(expr))
        }
        Expr::Call { callee, args, .. } => {
            if let Expr::Ident(name, _) = callee.as_ref() {
                if (name == "print" || name == "write") && args.len() == 1 {
                    if let Expr::String(s, _) = &args[0].value {
                        return if name == "print" {
                            format!("print(\"{}\")", escape_c(s))
                        } else {
                            format!("write(\"{}\")", escape_c(s))
                        };
                    }
                }
            }
            let a: Vec<_> = args.iter().map(|a| ex(&a.value)).collect();
            if let Expr::Member { object, field, .. } = callee.as_ref() {
                if let Expr::Ident(obj, _) = object.as_ref() {
                    if obj == "Task" && field == "Delay" {
                        return format!("Task_Delay({})", a.join(", "));
                    }
                    if obj == "Task" && (field == "WhenAll" || field == "WhenAny") {
                        if let Some(first) = args.first() {
                            if let Expr::ArrayLit(items, _) = &first.value {
                                let elems: Vec<_> = items.iter().map(ex).collect();
                                let fn_name = if field == "WhenAll" { "Task_WhenAll" } else { "Task_WhenAny" };
                                return format!(
                                    "{}((RtTask*[]){{ {} }}, {})",
                                    fn_name,
                                    elems.join(", "),
                                    items.len()
                                );
                            }
                        }
                    }
                    if obj == "CancellationTokenSource" && field == "New" {
                        return "CancellationTokenSource_New()".into();
                    }
                    if obj == "TaskGroup" && field == "New" {
                        return "TaskGroup_New()".into();
                    }
                    if (obj == "Gc" || obj == "GC") && field == "Collect" {
                        return "Gc_Collect()".into();
                    }
                    if (obj == "Gc" || obj == "GC") && field == "Stats" {
                        return "Gc_Stats()".into();
                    }
                }
                if let Some(ty) = lookup_type(object, types, vars, current) {
                    let mut full = vec![ex(object)];
                    full.extend(a);
                    return format!("{}_{}({})", ty, field, full.join(", "));
                }
            }
            format!("{}({})", ex(callee), a.join(", "))
        }
        Expr::Member { object, field, .. } => {
            if let Some(ty) = lookup_type(object, types, vars, current) {
                if ty == "CancellationTokenSource" && field == "Token" {
                    return format!("CancellationTokenSource_Token({})", ex(object));
                }
                if ty == "CancellationToken" && field == "IsCancellationRequested" {
                    return format!("CancellationToken_IsCancellationRequested({})", ex(object));
                }
            }
            let arrow = matches!(object.as_ref(), Expr::This(_))
                || lookup_type(object, types, vars, current).is_some();
            if arrow {
                format!("{}->{}", ex(object), field)
            } else {
                format!("{}.{}", ex(object), field)
            }
        }
        Expr::New { ty, args, .. } => {
            let a: Vec<_> = args.iter().map(|a| ex(&a.value)).collect();
            format!("{}_new({})", ty.name, a.join(", "))
        }
        Expr::Index { object, indices, .. } => {
            let idx = indices.first().map(ex).unwrap_or_else(|| "0".into());
            format!("{}[{}]", ex(object), idx)
        }
        Expr::ArrayLit(elems, _) => {
            let e: Vec<_> = elems.iter().map(ex).collect();
            format!("(/*array*/ {{ {} }})", e.join(", "))
        }
        Expr::Assign { target, op, value, .. } => {
            let o = match op {
                AssignOp::Assign => "=",
                AssignOp::Add => "+=",
                AssignOp::Sub => "-=",
                AssignOp::Mul => "*=",
                AssignOp::Div => "/=",
                AssignOp::Mod => "%=",
                AssignOp::BitAnd => "&=",
                AssignOp::BitOr => "|=",
                AssignOp::BitXor => "^=",
                AssignOp::Shl => "<<=",
                AssignOp::Shr => ">>=",
                AssignOp::NullCoalesce => "=",
            };
            if *op == AssignOp::NullCoalesce {
                format!(
                    "{} = (({}) ? ({}) : ({}))",
                    ex(target),
                    ex(target),
                    ex(target),
                    ex(value)
                )
            } else {
                format!("{} {} {}", ex(target), o, ex(value))
            }
        }
        Expr::Cast { ty, expr, .. } => {
            format!("(({})({}))", c_type_in(ty, types), ex(expr))
        }
        Expr::Deref(e, _) => format!("(*{})", ex(e)),
        Expr::AddressOf(e, _) => format!("(&{})", ex(e)),
        Expr::PtrMember { object, field, .. } => format!("{}->{}", ex(object), field),
        Expr::Grouped(e, _) => format!("({})", ex(e)),
        Expr::Ternary {
            cond,
            then_expr,
            else_expr,
            ..
        } => format!("({} ? {} : {})", ex(cond), ex(then_expr), ex(else_expr)),
        Expr::Await(e, _) => format!("await({})", ex(e)),
        Expr::TypeOf(ty, _) => format!("/*typeof {}*/0", ty.name),
        Expr::SizeOf(ty, _) => format!("(int64_t)sizeof({})", c_type_sizeof(ty, types)),
        Expr::OffsetOf { ty, field, .. } => {
            format!(
                "(int64_t)offsetof({}, {})",
                c_type_sizeof(ty, types),
                field
            )
        }
        Expr::Lambda { .. } => "/*lambda*/NULL".into(),
        Expr::Interpolated(parts, _) => {
            let (fmt, _) = interpolate_printf(parts, false, types, vars, current);
            fmt
        }
        _ => "/*expr*/0".into(),
    }
}

fn interpolate_printf(
    parts: &[InterpPart],
    newline: bool,
    types: &HashSet<String>,
    vars: &HashMap<String, String>,
    current: Option<&str>,
) -> (String, Vec<String>) {
    let mut fmt = String::from("\"");
    let mut args = Vec::new();
    for p in parts {
        match p {
            InterpPart::Literal(l) => fmt.push_str(&escape_c(l)),
            InterpPart::Expr(e) => {
                let (spec, arg) = printf_arg(e, types, vars, current);
                fmt.push('%');
                fmt.push_str(spec);
                args.push(arg);
            }
        }
    }
    if newline {
        fmt.push_str("\\n");
    }
    fmt.push('"');
    (fmt, args)
}

fn printf_arg(
    expr: &Expr,
    types: &HashSet<String>,
    vars: &HashMap<String, String>,
    current: Option<&str>,
) -> (&'static str, String) {
    let c = expr_to_c(expr, types, vars, current);
    match expr {
        Expr::Float(_, _) => ("g", format!("(double)({})", c)),
        Expr::String(_, _) | Expr::Interpolated(_, _) => ("s", c),
        Expr::Bool(_, _) => ("s", format!("(({}) ? \"true\" : \"false\")", c)),
        Expr::Char(_, _) => ("c", format!("(int)({})", c)),
        _ => ("lld", format!("(long long)({})", c)),
    }
}

fn infer_c_type(init: Option<&Expr>, types: &HashSet<String>) -> Option<String> {
    match init? {
        Expr::Float(_, _) => Some("double".into()),
        Expr::Bool(_, _) => Some("bool".into()),
        Expr::String(_, _) | Expr::Interpolated(_, _) => Some("const char*".into()),
        Expr::Char(_, _) => Some("char".into()),
        Expr::New { ty, .. } if types.contains(&ty.name) => Some(format!("{}*", ty.name)),
        _ => Some("int64_t".into()),
    }
}

fn escape_c(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\t', "\\t")
}

fn collect_ffi_headers(
    item: &Item,
    out: &mut String,
    seen: &mut std::collections::HashSet<String>,
) {
    match item {
        Item::Attribute(attr, inner) => {
            if attr.name.eq_ignore_ascii_case("include") {
                if let Some(h) = crate::ffi::attr_string(attr) {
                    if seen.insert(h.clone()) {
                        if h.starts_with('<') {
                            out.push_str(&format!("#include {}\n", h));
                        } else {
                            out.push_str(&format!("#include \"{}\"\n", h));
                        }
                    }
                }
            }
            if matches!(
                attr.name.to_ascii_lowercase().as_str(),
                "c" | "cembed" | "embed"
            ) {
                // embedded C is emitted later in emit_item to keep order with functions
            }
            collect_ffi_headers(inner, out, seen);
        }
        Item::Namespace(ns) => {
            for i in &ns.items {
                collect_ffi_headers(i, out, seen);
            }
        }
        _ => {}
    }
}

/// Collect linker inputs from program attributes (`[link:]`, `[DllImport:]`).
pub fn collect_link_libs(program: &Program) -> Vec<String> {
    let mut libs = Vec::new();
    fn walk(item: &Item, libs: &mut Vec<String>) {
        match item {
            Item::Attribute(attr, inner) => {
                if matches!(
                    attr.name.to_ascii_lowercase().as_str(),
                    "link" | "dllimport" | "lib"
                ) {
                    if let Some(s) = crate::ffi::attr_string(attr) {
                        if !libs.contains(&s) {
                            libs.push(s);
                        }
                    }
                }
                walk(inner, libs);
            }
            Item::Namespace(ns) => {
                for i in &ns.items {
                    walk(i, libs);
                }
            }
            Item::Function(f) => {
                for a in &f.attributes {
                    if matches!(
                        a.name.to_ascii_lowercase().as_str(),
                        "link" | "dllimport" | "lib"
                    ) {
                        if let Some(s) = crate::ffi::attr_string(a) {
                            if !libs.contains(&s) {
                                libs.push(s);
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }
    for item in &program.items {
        walk(item, &mut libs);
    }
    libs
}

fn attr_u64(attr: &Attribute) -> Option<u64> {
    match &attr.value {
        Some(Expr::Int(n, _)) => Some(*n as u64),
        Some(Expr::UInt(n, _)) => Some(*n),
        Some(Expr::String(s, _)) => {
            let s = s.trim();
            if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
                u64::from_str_radix(hex, 16).ok()
            } else {
                s.parse().ok()
            }
        }
        _ => None,
    }
}

fn program_has_attr(program: &Program, name: &str) -> bool {
    fn walk(item: &Item, name: &str) -> bool {
        match item {
            Item::Attribute(attr, inner) => {
                attr.name.eq_ignore_ascii_case(name) || walk(inner, name)
            }
            Item::Namespace(ns) => ns.items.iter().any(|i| walk(i, name)),
            _ => false,
        }
    }
    program.items.iter().any(|i| walk(i, name))
}

