//! Token definitions for RayTask.

use crate::span::Span;
use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    // Literals
    IntLit(i64),
    UIntLit(u64),
    FloatLit(f64),
    DecimalLit(String),
    CharLit(char),
    StringLit(String),
    RawStringLit(String),
    BoolLit(bool),
    Null,

    // Identifiers & keywords
    Ident(String),

    // Keywords
    Var,
    Dyn,
    Const,
    Class,
    Struct,
    Interface,
    Abstract,
    Static,
    Virtual,
    Override,
    New,
    Base,
    This,
    Super,
    Return,
    If,
    Else,
    Switch,
    Case,
    Default,
    Break,
    Continue,
    For,
    Foreach,
    While,
    Do,
    In,
    Try,
    Catch,
    Finally,
    Throw,
    Using,
    Unsafe,
    Stack,
    Owned,
    Async,
    Await,
    Match,
    Export,
    Protected,
    Private,
    Import,
    Namespace,
    Module,
    Property,
    Get,
    Set,
    Where,
    Operator,
    Params,
    Is,
    As,
    Typeof,
    Nameof,
    Sizeof,
    Offsetof,
    Asm,
    Volatile,
    Union,
    True,
    False,
    Void,
    Bool,
    Byte,
    SByte,
    Short,
    UShort,
    Int,
    UInt,
    Long,
    ULong,
    Float,
    Double,
    Decimal,
    Char,
    String,
    Ptr,

    // Operators & punctuation
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    AmpAmp,
    PipePipe,
    Bang,
    EqEq,
    BangEq,
    Lt,
    Gt,
    LtEq,
    GtEq,
    Amp,
    Pipe,
    Caret,
    Tilde,
    LtLt,
    GtGt,
    Eq,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    AmpEq,
    PipeEq,
    CaretEq,
    LtLtEq,
    GtGtEq,
    PlusPlus,
    MinusMinus,
    Arrow,      // =>
    ThinArrow,  // ->
    Question,
    QuestionQuestion, // ??
    QuestionQuestionEq, // ??=
    QuestionDot, // ?.
    DotDot,      // ..
    DotDotEq,    // ..=
    Dot,
    Comma,
    Colon,
    Semicolon,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    At, // @ for raw strings / attributes start handled differently

    // Attributes are parsed as [ident: value]
    Eof,
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenKind::Ident(s) => write!(f, "{}", s),
            TokenKind::IntLit(n) => write!(f, "{}", n),
            TokenKind::UIntLit(n) => write!(f, "{}", n),
            TokenKind::FloatLit(n) => write!(f, "{}", n),
            TokenKind::DecimalLit(s) => write!(f, "{}", s),
            TokenKind::CharLit(c) => write!(f, "'{}'", c),
            TokenKind::StringLit(s) => write!(f, "\"{}\"", s),
            TokenKind::RawStringLit(s) => write!(f, "@\"{}\"", s),
            TokenKind::BoolLit(b) => write!(f, "{}", b),
            TokenKind::Null => write!(f, "null"),
            TokenKind::Var => write!(f, "var"),
            TokenKind::Dyn => write!(f, "dyn"),
            TokenKind::Const => write!(f, "const"),
            TokenKind::Class => write!(f, "class"),
            TokenKind::Struct => write!(f, "struct"),
            TokenKind::Interface => write!(f, "interface"),
            TokenKind::Abstract => write!(f, "abstract"),
            TokenKind::Static => write!(f, "static"),
            TokenKind::Virtual => write!(f, "virtual"),
            TokenKind::Override => write!(f, "override"),
            TokenKind::New => write!(f, "new"),
            TokenKind::Base => write!(f, "base"),
            TokenKind::This => write!(f, "this"),
            TokenKind::Super => write!(f, "super"),
            TokenKind::Return => write!(f, "return"),
            TokenKind::If => write!(f, "if"),
            TokenKind::Else => write!(f, "else"),
            TokenKind::Switch => write!(f, "switch"),
            TokenKind::Case => write!(f, "case"),
            TokenKind::Default => write!(f, "default"),
            TokenKind::Break => write!(f, "break"),
            TokenKind::Continue => write!(f, "continue"),
            TokenKind::For => write!(f, "for"),
            TokenKind::Foreach => write!(f, "foreach"),
            TokenKind::While => write!(f, "while"),
            TokenKind::Do => write!(f, "do"),
            TokenKind::In => write!(f, "in"),
            TokenKind::Try => write!(f, "try"),
            TokenKind::Catch => write!(f, "catch"),
            TokenKind::Finally => write!(f, "finally"),
            TokenKind::Throw => write!(f, "throw"),
            TokenKind::Using => write!(f, "using"),
            TokenKind::Unsafe => write!(f, "unsafe"),
            TokenKind::Stack => write!(f, "stack"),
            TokenKind::Owned => write!(f, "owned"),
            TokenKind::Async => write!(f, "async"),
            TokenKind::Await => write!(f, "await"),
            TokenKind::Match => write!(f, "match"),
            TokenKind::Export => write!(f, "export"),
            TokenKind::Protected => write!(f, "protected"),
            TokenKind::Private => write!(f, "private"),
            TokenKind::Import => write!(f, "import"),
            TokenKind::Namespace => write!(f, "namespace"),
            TokenKind::Module => write!(f, "module"),
            TokenKind::Property => write!(f, "property"),
            TokenKind::Get => write!(f, "get"),
            TokenKind::Set => write!(f, "set"),
            TokenKind::Where => write!(f, "where"),
            TokenKind::Operator => write!(f, "operator"),
            TokenKind::Params => write!(f, "params"),
            TokenKind::Is => write!(f, "is"),
            TokenKind::As => write!(f, "as"),
            TokenKind::Typeof => write!(f, "typeof"),
            TokenKind::Nameof => write!(f, "nameof"),
            TokenKind::Sizeof => write!(f, "sizeof"),
            TokenKind::Offsetof => write!(f, "offsetof"),
            TokenKind::Asm => write!(f, "asm"),
            TokenKind::Volatile => write!(f, "volatile"),
            TokenKind::Union => write!(f, "union"),
            TokenKind::True => write!(f, "true"),
            TokenKind::False => write!(f, "false"),
            TokenKind::Void => write!(f, "void"),
            TokenKind::Bool => write!(f, "bool"),
            TokenKind::Byte => write!(f, "byte"),
            TokenKind::SByte => write!(f, "sbyte"),
            TokenKind::Short => write!(f, "short"),
            TokenKind::UShort => write!(f, "ushort"),
            TokenKind::Int => write!(f, "int"),
            TokenKind::UInt => write!(f, "uint"),
            TokenKind::Long => write!(f, "long"),
            TokenKind::ULong => write!(f, "ulong"),
            TokenKind::Float => write!(f, "float"),
            TokenKind::Double => write!(f, "double"),
            TokenKind::Decimal => write!(f, "decimal"),
            TokenKind::Char => write!(f, "char"),
            TokenKind::String => write!(f, "string"),
            TokenKind::Ptr => write!(f, "ptr"),
            TokenKind::Plus => write!(f, "+"),
            TokenKind::Minus => write!(f, "-"),
            TokenKind::Star => write!(f, "*"),
            TokenKind::Slash => write!(f, "/"),
            TokenKind::Percent => write!(f, "%"),
            TokenKind::AmpAmp => write!(f, "&&"),
            TokenKind::PipePipe => write!(f, "||"),
            TokenKind::Bang => write!(f, "!"),
            TokenKind::EqEq => write!(f, "=="),
            TokenKind::BangEq => write!(f, "!="),
            TokenKind::Lt => write!(f, "<"),
            TokenKind::Gt => write!(f, ">"),
            TokenKind::LtEq => write!(f, "<="),
            TokenKind::GtEq => write!(f, ">="),
            TokenKind::Amp => write!(f, "&"),
            TokenKind::Pipe => write!(f, "|"),
            TokenKind::Caret => write!(f, "^"),
            TokenKind::Tilde => write!(f, "~"),
            TokenKind::LtLt => write!(f, "<<"),
            TokenKind::GtGt => write!(f, ">>"),
            TokenKind::Eq => write!(f, "="),
            TokenKind::PlusEq => write!(f, "+="),
            TokenKind::MinusEq => write!(f, "-="),
            TokenKind::StarEq => write!(f, "*="),
            TokenKind::SlashEq => write!(f, "/="),
            TokenKind::PercentEq => write!(f, "%="),
            TokenKind::AmpEq => write!(f, "&="),
            TokenKind::PipeEq => write!(f, "|="),
            TokenKind::CaretEq => write!(f, "^="),
            TokenKind::LtLtEq => write!(f, "<<="),
            TokenKind::GtGtEq => write!(f, ">>="),
            TokenKind::PlusPlus => write!(f, "++"),
            TokenKind::MinusMinus => write!(f, "--"),
            TokenKind::Arrow => write!(f, "=>"),
            TokenKind::ThinArrow => write!(f, "->"),
            TokenKind::Question => write!(f, "?"),
            TokenKind::QuestionQuestion => write!(f, "??"),
            TokenKind::QuestionQuestionEq => write!(f, "??="),
            TokenKind::QuestionDot => write!(f, "?."),
            TokenKind::DotDot => write!(f, ".."),
            TokenKind::DotDotEq => write!(f, "..="),
            TokenKind::Dot => write!(f, "."),
            TokenKind::Comma => write!(f, ","),
            TokenKind::Colon => write!(f, ":"),
            TokenKind::Semicolon => write!(f, ";"),
            TokenKind::LParen => write!(f, "("),
            TokenKind::RParen => write!(f, ")"),
            TokenKind::LBrace => write!(f, "{{"),
            TokenKind::RBrace => write!(f, "}}"),
            TokenKind::LBracket => write!(f, "["),
            TokenKind::RBracket => write!(f, "]"),
            TokenKind::At => write!(f, "@"),
            TokenKind::Eof => write!(f, "<EOF>"),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
    pub lexeme: String,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span, lexeme: impl Into<String>) -> Self {
        Self {
            kind,
            span,
            lexeme: lexeme.into(),
        }
    }

    pub fn is_eof(&self) -> bool {
        matches!(self.kind, TokenKind::Eof)
    }
}

pub fn keyword(ident: &str) -> Option<TokenKind> {
    Some(match ident {
        "var" => TokenKind::Var,
        "dyn" => TokenKind::Dyn,
        "const" => TokenKind::Const,
        "class" => TokenKind::Class,
        "struct" => TokenKind::Struct,
        "interface" => TokenKind::Interface,
        "abstract" => TokenKind::Abstract,
        "static" => TokenKind::Static,
        "virtual" => TokenKind::Virtual,
        "override" => TokenKind::Override,
        "new" => TokenKind::New,
        "base" => TokenKind::Base,
        "this" => TokenKind::This,
        "super" => TokenKind::Super,
        "return" => TokenKind::Return,
        "if" => TokenKind::If,
        "else" => TokenKind::Else,
        "switch" => TokenKind::Switch,
        "case" => TokenKind::Case,
        "default" => TokenKind::Default,
        "break" => TokenKind::Break,
        "continue" => TokenKind::Continue,
        "for" => TokenKind::For,
        "foreach" => TokenKind::Foreach,
        "while" => TokenKind::While,
        "do" => TokenKind::Do,
        "in" => TokenKind::In,
        "try" => TokenKind::Try,
        "catch" => TokenKind::Catch,
        "finally" => TokenKind::Finally,
        "throw" => TokenKind::Throw,
        "using" => TokenKind::Using,
        "unsafe" => TokenKind::Unsafe,
        "stack" => TokenKind::Stack,
        "owned" => TokenKind::Owned,
        "async" => TokenKind::Async,
        "await" => TokenKind::Await,
        "match" => TokenKind::Match,
        "export" => TokenKind::Export,
        "protected" => TokenKind::Protected,
        "private" => TokenKind::Private,
        "import" => TokenKind::Import,
        "namespace" => TokenKind::Namespace,
        "module" => TokenKind::Module,
        "property" => TokenKind::Property,
        "get" => TokenKind::Get,
        "set" => TokenKind::Set,
        "where" => TokenKind::Where,
        "operator" => TokenKind::Operator,
        "params" => TokenKind::Params,
        "is" => TokenKind::Is,
        "as" => TokenKind::As,
        "typeof" => TokenKind::Typeof,
        "nameof" => TokenKind::Nameof,
        "sizeof" => TokenKind::Sizeof,
        "offsetof" => TokenKind::Offsetof,
        "asm" => TokenKind::Asm,
        "volatile" => TokenKind::Volatile,
        "union" => TokenKind::Union,
        "true" => TokenKind::True,
        "false" => TokenKind::False,
        "null" => TokenKind::Null,
        "void" => TokenKind::Void,
        "bool" => TokenKind::Bool,
        "byte" => TokenKind::Byte,
        "sbyte" => TokenKind::SByte,
        "short" => TokenKind::Short,
        "ushort" => TokenKind::UShort,
        "int" => TokenKind::Int,
        "uint" => TokenKind::UInt,
        "long" => TokenKind::Long,
        "ulong" => TokenKind::ULong,
        "float" => TokenKind::Float,
        "double" => TokenKind::Double,
        "decimal" => TokenKind::Decimal,
        "char" => TokenKind::Char,
        "string" => TokenKind::String,
        "ptr" => TokenKind::Ptr,
        _ => return None,
    })
}
