//! Token definitions for RayTask.

use crate::span::Span;
use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    // Literals
    IntLit(i64),
    UIntLit(u64),
    FloatLit(f64),
    DecimalLit(String),
    CharLit(char),
    StringLit(String),
    RawStringLit(String),
    BoolLit(bool),
    Null,

    // Identifiers & keywords
    Ident(String),

    // Keywords
    Var,
    Dyn,
    Const,
    Class,
    Struct,
    Interface,
    Abstract,
    Static,
    Virtual,
    Override,
    New,
    Base,
    This,
    Super,
    Return,
    If,
    Else,
    Switch,
    Case,
    Default,
    Break,
    Continue,
    For,
    Foreach,
    While,
    Do,
    In,
    Try,
    Catch,
    Finally,
    Throw,
    Using,
    Unsafe,
    Stack,
    Owned,
    Async,
    Await,
    Match,
    Export,
    Protected,
    Private,
    Import,
    Namespace,
    Module,
    Property,
    Get,
    Set,
    Where,
    Operator,
    Params,
    Is,
    As,
    Typeof,
    Sizeof,
    Offsetof,
    Asm,
    Volatile,
    Union,
    True,
    False,
    Void,
    Bool,
    Byte,
    SByte,
    Short,
    UShort,
    Int,
    UInt,
    Long,
    ULong,
    Float,
    Double,
    Decimal,
    Char,
    String,
    Ptr,

    // Operators & punctuation
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    AmpAmp,
    PipePipe,
    Bang,
    EqEq,
    BangEq,
    Lt,
    Gt,
    LtEq,
    GtEq,
    Amp,
    Pipe,
    Caret,
    Tilde,
    LtLt,
    GtGt,
    Eq,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    AmpEq,
    PipeEq,
    CaretEq,
    LtLtEq,
    GtGtEq,
    PlusPlus,
    MinusMinus,
    Arrow,      // =>
    ThinArrow,  // ->
    Question,
    QuestionQuestion, // ??
    QuestionQuestionEq, // ??=
    QuestionDot, // ?.
    DotDot,      // ..
    DotDotEq,    // ..=
    Dot,
    Comma,
    Colon,
    Semicolon,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    At, // @ for raw strings / attributes start handled differently

    // Attributes are parsed as [ident: value]
    Eof,
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenKind::Ident(s) => write!(f, "{}", s),
            TokenKind::IntLit(n) => write!(f, "{}", n),
            TokenKind::StringLit(s) => write!(f, "\"{}\"", s),
            other => write!(f, "{:?}", other),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
    pub lexeme: String,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span, lexeme: impl Into<String>) -> Self {
        Self {
            kind,
            span,
            lexeme: lexeme.into(),
        }
    }

    pub fn is_eof(&self) -> bool {
        matches!(self.kind, TokenKind::Eof)
    }
}

pub fn keyword(ident: &str) -> Option<TokenKind> {
    Some(match ident {
        "var" => TokenKind::Var,
        "dyn" => TokenKind::Dyn,
        "const" => TokenKind::Const,
        "class" => TokenKind::Class,
        "struct" => TokenKind::Struct,
        "interface" => TokenKind::Interface,
        "abstract" => TokenKind::Abstract,
        "static" => TokenKind::Static,
        "virtual" => TokenKind::Virtual,
        "override" => TokenKind::Override,
        "new" => TokenKind::New,
        "base" => TokenKind::Base,
        "this" => TokenKind::This,
        "super" => TokenKind::Super,
        "return" => TokenKind::Return,
        "if" => TokenKind::If,
        "else" => TokenKind::Else,
        "switch" => TokenKind::Switch,
        "case" => TokenKind::Case,
        "default" => TokenKind::Default,
        "break" => TokenKind::Break,
        "continue" => TokenKind::Continue,
        "for" => TokenKind::For,
        "foreach" => TokenKind::Foreach,
        "while" => TokenKind::While,
        "do" => TokenKind::Do,
        "in" => TokenKind::In,
        "try" => TokenKind::Try,
        "catch" => TokenKind::Catch,
        "finally" => TokenKind::Finally,
        "throw" => TokenKind::Throw,
        "using" => TokenKind::Using,
        "unsafe" => TokenKind::Unsafe,
        "stack" => TokenKind::Stack,
        "owned" => TokenKind::Owned,
        "async" => TokenKind::Async,
        "await" => TokenKind::Await,
        "match" => TokenKind::Match,
        "export" => TokenKind::Export,
        "protected" => TokenKind::Protected,
        "private" => TokenKind::Private,
        "import" => TokenKind::Import,
        "namespace" => TokenKind::Namespace,
        "module" => TokenKind::Module,
        "property" => TokenKind::Property,
        "get" => TokenKind::Get,
        "set" => TokenKind::Set,
        "where" => TokenKind::Where,
        "operator" => TokenKind::Operator,
        "params" => TokenKind::Params,
        "is" => TokenKind::Is,
        "as" => TokenKind::As,
        "typeof" => TokenKind::Typeof,
        "sizeof" => TokenKind::Sizeof,
        "offsetof" => TokenKind::Offsetof,
        "asm" => TokenKind::Asm,
        "volatile" => TokenKind::Volatile,
        "union" => TokenKind::Union,
        "true" => TokenKind::True,
        "false" => TokenKind::False,
        "null" => TokenKind::Null,
        "void" => TokenKind::Void,
        "bool" => TokenKind::Bool,
        "byte" => TokenKind::Byte,
        "sbyte" => TokenKind::SByte,
        "short" => TokenKind::Short,
        "ushort" => TokenKind::UShort,
        "int" => TokenKind::Int,
        "uint" => TokenKind::UInt,
        "long" => TokenKind::Long,
        "ulong" => TokenKind::ULong,
        "float" => TokenKind::Float,
        "double" => TokenKind::Double,
        "decimal" => TokenKind::Decimal,
        "char" => TokenKind::Char,
        "string" => TokenKind::String,
        "ptr" => TokenKind::Ptr,
        _ => return None,
    })
}
